### ISSUE TITLE
Remove limit of releases to keep

### ISSUE THREAD

**Issue by rui-ferreira** [dev-drprasad/delete-older-releases#17]
https://github.com/dev-drprasad/delete-older-releases/blob/9e9bf5d97e27ec9ce09839c7a67a1d4a63bc4068/index.js#L76

This line will limit the number of releases to keep to 100. So, for example, if I have a total of 200 releases and want to keep the latest 110, the script will never delete any release/tag, because the call response is capped to 100. 
Ideally you would adjust this call parameter considering the value of the `keep_latest` parameter.

**Comment by steve02081504** [comment]
> I think the max value for `per_page` on this endpoint is 100, not 1000 (or 500)
> 
> https://api.github.com/repos/aquasecurity/tfsec/releases?per_page=500
> 
> returns the first 100 items

https://github.com/badges/shields/issues/6766#issuecomment-880143026

**Comment by thadguidry** [comment]
The GitHub docs are clear:

------

**per_page** integer
The number of results per page (max 100).

Default: 30

------

**page** integer
Page number of the results to fetch.

Default: 1

------

In this function, https://github.com/dev-drprasad/delete-older-releases/blob/9e9bf5d97e27ec9ce09839c7a67a1d4a63bc4068/index.js#L71 

However, we currently **do not iterate** through all the pages, since we don't also include the path parameter `page=${page}` but only hardcoded with `path: repos/${owner}/${repo}/releases?per_page=100` but we could certainly add an iterative loop to increment that page parameter until a `404 Resource not found` is returned from the Releases API.  That would then give us a full set of releases and all their ids and continue to store all the results for various filtering mechanisms we have in the current `data` array used by the `deleteOlderReleases` function.

So, yes, I think this is a valid enhancement request and could be worked on by anyone and fairly straightforward I think.
